### ISSUE TITLE
IE fixed socks proxy parsed as http

### ISSUE THREAD

**Issue by lwahonen** [MarkusBernhardt/proxy-vole#10]
How to repro:

1) Go to IE settings pane, set up a socks proxy
2) Look at the ProtocolDispatchSelector you get from ProxySearch proxySearch = ProxySearch.getDefaultProxySearch().getProxySelector();

Expected: The proxy inside the ProtocolDispatchSelector has type SOCKS, network connectivity works
Reality: The proxy inside the ProtocolDispatchSelector has type HTTP, network connectivity doesn't work

I hotfixed this w/ the patch below, but it doesn't seem right - for some reason the proxy doesn't work if it's not set as the fallback selector.

--- a/src/main/java/com/github/markusbernhardt/proxy/search/browser/ie/IEProxySearchStrategy.java
+++ b/src/main/java/com/github/markusbernhardt/proxy/search/browser/ie/IEProxySearchStrategy.java
@@ -143,9 +144,14 @@ public class IEProxySearchStrategy implements ProxySearchStrategy {
                addSelectorForProtocol(p, "https", ps);
                addSelectorForProtocol(p, "ftp", ps);
                addSelectorForProtocol(p, "gopher", ps);
-               addSelectorForProtocol(p, "socks", ps);
                addFallbackSelector(p, ps);

+               if(p.containsKey("socks"))
+               {
+                       String socks = p.getProperty("socks");
+                       String[] fo=socks.split(":");
+                       ps.fallbackSelector=new FixedSocksSelector(fo[0], Integer.parseInt(fo[1]));
+               }
                ProxySelector result = setByPassListOnSelector(bypassList, ps);
                return result;
        }

**Comment by OnixGH** [comment]
> I hotfixed this w/ the patch below, but it doesn't seem right - for some reason the proxy doesn't work if it's not set as the fallback selector.

I believe this is caused by the use case where you only configure a SOCKS proxy in IE (i.e. fill in the SOCKS proxy line, and clear the HTTP/etc. lines).

The ProtocolDispatchSelector will try to lookup a selector using the `protocol` as the key, which would usually be `http`, and then comes up empty because there is no HTTP proxy configured (and the system fallback default is also empty).

But the above configuration actually means that the SOCKS proxy should rightly be used as the fallback, which is exactly how you patched it.
