### ISSUE TITLE
Information request - Does proxy-vole support DHCP?

### ISSUE THREAD

**Issue by NameetaJain** [MarkusBernhardt/proxy-vole#22]
We have tested DNS from proxy-vole, it works fine. Does it also support DHCP?
I have read in logs, Searching per DHCP is not supported. What does that mean?

**Comment by phansson** [comment]
I don't claim to be an expert as I'm not the author. However, this is my understanding of fhe current status for WPAD-DHCP:


**non-Windows:**  Someone has created some classes for it (probably years ago, I guess it must have been the original author), but it was never activated. I suppose DHCP queries isn't that easy to do correctly in Java without using a specialized library for the purpose. Anyway, the reasons why it was never fully implemented is just guesswork on my part. 

**Windows**:  Proxy-vole will outsource WPAD resolution to Windows. It will call windows function [WinHttpDetectAutoProxyConfigUrl](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384094(v=vs.85).aspx). This Windows function supports both DHCP and DNS. So in this case DHCP is supported. However, there's a [bug](https://github.com/MarkusBernhardt/proxy-vole/issues/6) with an [associated pull request](https://github.com/MarkusBernhardt/proxy-vole/pull/21) awaiting integration. This bug stops WPAD resolution working altogether on Windows, whether using DHCP, DNS or both.

Note, that also [some browsers do not support DHCP discovery](http://findproxyforurl.com/browser-support/) on some platforms, so in this respect proxy-vole is not alone. Because of this lack of support, I suppose that few - if any - sites actually use DHCP as the sole means of PAC file discovery. Therefore it can be argued that it is not *very* important for proxy-vole to support WPAD-DHCP.

**Comment by MarkusBernhardt** [comment]
As phansson has stated DHCP is a No-Go in Java. AFAIK DHCP works on MAC level and there is no way to implement that with standard JDK classes. Perhaps this could be implemented using JNI on Linux and OSX.

If this is really, really needed somewhere I will look into that again.

Btw. the patch for Windows will be released shortly.
