### ISSUE TITLE
Proxy-vole not able to parse PAC file when space in IP address in pac java script

### ISSUE THREAD

**Issue by NameetaJain** [MarkusBernhardt/proxy-vole#25]
We noticed one scenario, where proxy-vole is returning JS Evaluation error.
The PAC Java Script file contained space in IP address, for e.g.
"5.32.00.10 "

Expected:
Parser should trim spaces and successfully parse in such scenarios. We observed other libraries successfully parse this file.

**Comment by MarkusBernhardt** [comment]
Hi NameetaJain,

I tested all kinds of whitespace in the returned Proxy IP. Could not find a problem.
Closing this issue for now. If you have a test case for me, please reopen this issue.

Regards,
Markus

**Comment by Maxoudela** [comment]
Hi, 

Could we reopen this issue? 
Consider the following declaration in the proxy-pac file : 
`isInNet(myIpAddress(), "10.112.190.0", "255.255.255.0 ")`

A trailing space has been added after the last 0. We will then go into the isInNet method of PacScriptMethods, then in parseIpToLong : 
```
private long parseIpAddressToLong(String address) {
		long result = 0;
		String[] parts = address.split("\\.");
		long shift = 24;
		for (String part : parts) {
			long lpart = Long.parseLong(part);

			result |= (lpart << shift);
			shift -= 8;
		}
		return result;
	}
```
The parseLong will fail when it will try to parse the "0 " with the trailing space. I recommand doing a "part.trim()" in order to prevent such cases. 
I can make a PR if you want.
