### ISSUE TITLE
Requires huge dependencies

### ISSUE THREAD

**Issue by GladeDiviney** [MarkusBernhardt/proxy-vole#67]
This library adds 5MB to my distribution size -- is there any way to shrink it?

**Comment by gschnepp** [comment]
Who talks about 5 MB today?

BTW: Future versions may change away from Nashorn (again) to any other JavaScript library which will add some more dependencies. Proxy-vole's used Mozillas Rhino engine in the past but switched to Nashorn due to the amount of dependencies already. Unfortunately, Nashorn a) performs not that well in edge cases it seems (exceptions with no real cause in my case) and b) is marked for removal from JRE/JDK. So dependencies size will increase in either way.

Guido

**Comment by GladeDiviney** [comment]
Thanks for the update. 5MB is not a big deal in a lot of cases but in our case it feels overweight to solve a single, very specific networking issue.
